# Generated by Django 4.2.27 on 2025-12-05 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_no', models.CharField(max_length=20)),
                ('airline', models.CharField(max_length=50)),
                ('plane_type', models.CharField(max_length=50)),
                ('depart_time', models.DateTimeField()),
                ('arrive_time', models.DateTimeField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ON_SALE', '在售'), ('CANCELLED', '已取消'), ('FINISHED', '已结束')], default='ON_SALE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrive_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrive_flights', to='flights.airport')),
                ('depart_airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depart_flights', to='flights.airport')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_class', models.CharField(choices=[('ECONOMY', '经济舱'), ('BUSINESS', '公务舱'), ('FIRST', '头等舱')], max_length=20)),
                ('total_seats', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='flights.flight')),
            ],
            options={
                'unique_together': {('flight', 'cabin_class')},
            },
        ),
    ]
