# Generated by Django 4.2.27 on 2025-12-05 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(choices=[('PAID', '已支付'), ('CANCELLED', '已取消'), ('REFUNDING', '退票中'), ('REFUNDED', '已退票')], default='PAID', max_length=20)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flights.flight')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='accounts.passengerprofile')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='flights.flightseat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('approve_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已同意'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refund_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_record', to='orders.ticketorder')),
            ],
        ),
    ]
